### ISSUE TITLE
Connection fails unless dashboard is connected

### ISSUE THREAD

**Issue by phyroslam** [CoreProc/nova-echo#4]
Hi, I think I am experiencing something very similar to this issue: [https://github.com/beyondcode/laravel-websockets/issues/439](https://github.com/beyondcode/laravel-websockets/issues/439) it seems that I need to add enabledTransports: ['ws', 'wss'] to the laravel echo configuration but not sure how to add this in this package. I already tried going to the vendor file and editing the source file and run npm run dev but that is giving me some other errors. Is there a way to add that configuration to the nova-echo client?

**Comment by Delaney** [comment]
Hello @phyroslam were you able to solve this?
